# Generated by Django 3.2.2 on 2022-03-08 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20220305_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='shared_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
